version: "3"

silent: true

tasks:
  bootstrap:
    aliases: [bs]
    cmds:
      - "echo [SleekVim] Bootstrapping"
      - task: clean_paths_linux
      - task: clean_paths_windows
      - task: clone_lazy
      - task: install_all

  clean_paths_linux:
    aliases: [cpl]
    platforms: [linux]
    cmds:
      - "echo [SleekVim] {{.TASK}}"
      - rm -rf ~/.cache/nvim
      - rm -rf ~/.local/share/nvim
      - rm -rf ~/.local/state/nvim

  clean_paths_windows:
    aliases: [cpw]
    platforms: [windows]
    cmds:
      - "echo [SleekVim] {{.TASK}}"
      - powershell rm {{.TMP}}/nvim -r -f -ErrorAction SilentlyContinue
      - powershell rm {{.LOCALAPPDATA}}/nvim-data -r -f -ErrorAction SilentlyContinue

  clone_lazy:
    aliases: [cl]
    cmds:
      - "echo [SleekVim] {{.TASK}}"
      - cmd: git clone --filter=blob:none --single-branch https://github.com/folke/lazy.nvim ~/.local/share/nvim/lazy/lazy.nvim
        platforms: [linux]
      - cmd: git clone --filter=blob:none --single-branch https://github.com/folke/lazy.nvim {{.LOCALAPPDATA}}/nvim-data/lazy/lazy.nvim
        platforms: [windows]

  install_all:
    aliases: [ia]
    cmds:
      - "echo [SleekVim] {{.TASK}}"
      - task: install_plugins
      - task: install_treesitter
      - task: install_tools

  install_plugins:
    aliases: [ip]
    cmds:
      - "echo [SleekVim] {{.TASK}}"
      - task: nvim_cmd
        vars: { CMD: "Lazy! install" }

  install_treesitter:
    aliases: [its]
    cmds:
      - "echo [SleekVim] {{.TASK}}"
      - task: nvim_cmd
        vars: { CMD: "TSInstallSync" }

  install_tools:
    aliases: [it]
    cmds:
      - "echo [SleekVim] {{.TASK}}"
      - task: nvim_cmd
        vars: { CMD: "MasonToolsInstallSync" }

  update_all:
    aliases: [ua]
    cmds:
      - "echo [SleekVim] {{.TASK}}"
      - task: update_plugins
      - task: update_treesitter
      - task: update_tools

  update_plugins:
    aliases: [up]
    cmds:
      - "echo [SleekVim] {{.TASK}}"
      - task: nvim_cmd
        vars: { CMD: "Lazy! sync" }

  update_treesitter:
    aliases: [uts]
    cmds:
      - "echo [SleekVim] {{.TASK}}"
      - task: nvim_cmd
        vars: { CMD: "TSUpdateSync" }

  update_tools:
    aliases: [ut]
    cmds:
      - "echo [SleekVim] {{.TASK}}"
      - task: nvim_cmd
        vars: { CMD: "MasonToolsUpdateSync" }

  nvim_cmd:
    silent: true
    cmds:
      - nvim --headless -c '{{.CMD}}' -c 'echo "\n"' -c 'qa'
