local o = vim.opt

o.autoindent = true
o.background = 'dark'
o.backup = false
o.clipboard = 'unnamedplus'
o.cmdheight = 1
o.copyindent = true
o.cursorline = true
o.expandtab = true
o.foldenable = false
o.laststatus = 3
o.linebreak = true
o.more = false
o.mouse = 'a'
o.number = false
o.relativenumber = false
o.scrolloff = 8
o.shiftround = true
o.shiftwidth = 4
o.shortmess:append({ I = true, S = true, s = true })
o.showbreak = '󱞪 '
o.showcmd = false
o.showmode = false
o.signcolumn = 'auto'
o.splitbelow = true
o.splitright = true
o.swapfile = false
o.tabstop = 4
o.termguicolors = true
o.title = true
o.titlestring = '%{expand("%:p:~")} - NVIM'
o.undofile = true
o.updatetime = 1000
o.writebackup = false
