require("aerial").setup({
	attach_mode = "global",
	backends = {
		"lsp",
		"treesitter",
		"markdown",
		"man",
	},
	disable_max_lines = 20000,
	filter_kind = false,
	highlight_mode = "last",
	keymaps = {
		["?"] = "actions.show_help",
		-- ["g?"] = "actions.show_help",
		["<CR>"] = "actions.jump",
		["<2-LeftMouse>"] = "actions.jump",
		-- ["<C-v>"] = "actions.jump_vsplit",
		-- ["<C-s>"] = "actions.jump_split",
		["o"] = "actions.scroll",
		["<C-j>"] = "actions.down_and_scroll",
		["<C-k>"] = "actions.up_and_scroll",
		-- ["{"] = "actions.prev",
		-- ["}"] = "actions.next",
		["h"] = "actions.prev_up",
		["H"] = "actions.next_up",
		["q"] = "actions.close",
		["l"] = "actions.tree_toggle",
		-- ["za"] = "actions.tree_toggle",
		-- ["O"] = "actions.tree_toggle_recursive",
		-- ["zA"] = "actions.tree_toggle_recursive",
		["zr"] = "actions.tree_increase_fold_level",
		["zR"] = "actions.tree_open_all",
		["zm"] = "actions.tree_decrease_fold_level",
		["zM"] = "actions.tree_close_all",
	},
	layout = {
		default_direction = "right",
		placement = "edge",
		width = 40,
	},
	lsp = { update_delay = 800 },
	post_jump_cmd = "normal! zt",
	show_guides = true,
	treesitter = { update_delay = 800 },
})
