local gitIcons = {
    added = " ",
    modified = " ",
    removed = " ",
}

require 'lspkind'.init {
    mode = 'symbol_text',
    preset = 'default',
    symbol_map = {
        Array = " ",
        Boolean = " ",
        Class = " ",
        Color = " ",
        Constant = "󰏿 ",
        Constructor = "󱌢 ",
        Copilot = " ",
        Enum = " ",
        EnumMember = " ",
        Event = " ",
        Field = " ",
        File = " ",
        Folder = " ",
        Function = "󰊕 ",
        Interface = " ",
        Key = " ",
        Keyword = " ",
        Method = "󰡱 ",
        Module = " ",
        Namespace = "󰰓 ",
        Null = "󰟢 ",
        Number = " ",
        Object = " ",
        Operator = " ",
        Package = " ",
        Property = " ",
        Reference = " ",
        Snippet = " ",
        String = " ",
        Struct = " ",
        Text = " ",
        TypeParameter = " ",
        Unit = " ",
        Value = " ",
        Variable = "󰫧 ",
    },
}
