require 'lspsaga'.setup {
    beacon = {
        enable = false,
        frequency = 7,
    },
    callhierarchy = {
        show_detail = true,
        keys = {
            edit = "e",
            vsplit = "s",
            split = "i",
            tabe = "t",
            jump = "o",
            quit = "q",
            expand_collapse = "u",
        },
    },
    code_action = {
        extend_gitsigns = false,
        keys = { quit = "q", exec = "<CR>" },
        num_shortcut = true,
        show_server_name = false,
    },
    definition = {
        edit = "<C-c>o",
        vsplit = "<C-c>v",
        split = "<C-c>i",
        tabe = "<C-c>t",
        quit = "q",
    },
    diagnostic = {
        border_follow = false,
        extend_relatedInformation = false,
        insert_winblend = 0,
        jump_num_shortcut = true,
        keys = {
            exec_action = 'o',
            quit = 'q',
            expand_or_jump = '<CR>',
            quit_in_show = { 'q', '<ESC>' },
        },
        max_height = 0.7,
        max_show_height = 0.7,
        max_show_width = 0.9,
        max_width = 0.8,
        on_insert = false,
        on_insert_follow = false,
        show_code_action = true,
        show_source = false,
        text_hl_follow = true,
    },
    finder = {
        max_height = 0.5,
        min_width = 30,
        force_max_height = false,
        keys = {
            jump_to = 'p',
            expand_or_jump = 'o',
            vsplit = 's',
            split = 'i',
            tabe = 't',
            tabnew = 'r',
            quit = { 'q', '<ESC>' },
            close_in_preview = '<ESC>',
        },
    },
    hover = {
        max_width = 0.8,
        open_link = 'gx',
        open_browser = '!chrome',
    },
    lightbulb = {
        enable = false,
        enable_in_insert = false,
        sign = false,
        sign_priority = 40,
        virtual_text = true,
    },
    outline = {
        auto_close = true,
        auto_preview = true,
        auto_refresh = false,
        custom_sort = nil,
        keys = { expand_or_jump = 'o', quit = "q" },
        preview_width = 0.4,
        show_detail = true,
        win_position = "right",
        win_width = 30,
        win_with = "",
    },
    preview = {
        lines_above = 0,
        lines_below = 2,
    },
    scroll_preview = {
        scroll_down = "<C-f>",
        scroll_up = "<C-b>",
    },
    symbol_in_winbar = {
        color_mode = true,
        enable = false,
        folder_level = 2,
        hide_keyword = true,
        ignore_patterns = {},
        respect_root = false,
        separator = " ",
        show_file = true,
    },
    ui = {
        border = "rounded",
        code_action = "💡",
        collapse = "",
        expand = "",
        hover = ' ',
        incoming = " ",
        kind = {},
        outgoing = " ",
        title = false,
        winblend = 0,
    },
}
